spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/QuestApp
    username: postgres
    password: root
    river-class-name: org.postgresql.Driver